import { existsSync } from 'fs';
import { resolve } from 'path';
import { execSync } from 'child_process';

export default function globalSetup(): void {
  // Sitemaps and other build artifacts (e.g. dist/sitemap-index.xml) are
  // generated by `astro build`, not `astro dev`. CI always builds before
  // running tests; locally we build on demand when dist/ is missing so
  // sitemap tests can assert against real output.
  const projectRoot = resolve(import.meta.dirname, '..');
  if (!existsSync(resolve(projectRoot, 'dist', 'sitemap-index.xml'))) {
    execSync('npm run build', { cwd: projectRoot, stdio: 'inherit' });
  }
}
